# Generated by Django 6.0.5 on 2026-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=200)),
            ],
        ),
    ]
