# Generated by Django 6.0.5 on 2026-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
